/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './unlv-oe-footer';
import * as i2 from '@angular/common';
export const UnlvOeFooterModuleNgFactory:i0.NgModuleFactory<i1.UnlvOeFooterModule> = i0.ɵcmf(i1.UnlvOeFooterModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.UnlvOeFooterModule,i1.UnlvOeFooterModule,
          ([] as any[]))]);
    });
const styles_UnlvOeFooter:any[] = ['.unlv-oe-footer[_ngcontent-%COMP%] {\n        height: 5.25rem;\n        width: 100%;\n        position: absolute;\n        left: 0;\n        bottom: 0;\n        text-align: center;\n        display: block;\n    }\n    .unlv-oe-footer[_ngcontent-%COMP%]   img.oe-logo[_ngcontent-%COMP%] {\n        max-width: 100%;\n        width: 300px;\n        margin-bottom: .25rem;\n    }\n    .unlv-oe-footer[_ngcontent-%COMP%]   p.copyright[_ngcontent-%COMP%] {\n        margin: 0;\n        font-size: .75rem;\n    }'];
export const RenderType_UnlvOeFooter:i0.RendererType2 = i0.ɵcrt({encapsulation:0,styles:styles_UnlvOeFooter,
    data:{}});
export function View_UnlvOeFooter_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),10,'footer',[['class','unlv-oe-footer']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    	'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class','container']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'a',[['href','//online.unlv.edu'],['target','_blank']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),0,'img',[['alt','UNLV Online Education Logo'],
              ['class','oe-logo'],['src','//online.unlv.edu/sites/online.unlv.edu.oedrupal/libraries/base/Online_Education_500w_trimmed.png']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'p',[['class','copyright']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    			© ',' UNLV Online Education\n    		'])),(_l()(),i0.ɵted((null as any),
          ['\n    	'])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n  ']))],(null as any),(_ck,_v) => {
    var _co:i1.UnlvOeFooter = _v.component;
    const currVal_0:any = _co.copyright;
    _ck(_v,9,0,currVal_0);
  });
}
export function View_UnlvOeFooter_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'unlv-oe-footer',
      ([] as any[]),(null as any),(null as any),(null as any),View_UnlvOeFooter_0,
      RenderType_UnlvOeFooter)),i0.ɵdid(114688,(null as any),0,i1.UnlvOeFooter,([] as any[]),
      (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const UnlvOeFooterNgFactory:i0.ComponentFactory<i1.UnlvOeFooter> = i0.ɵccf('unlv-oe-footer',
    i1.UnlvOeFooter,View_UnlvOeFooter_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbXVycGh5MTEvRG9jdW1lbnRzL3d3dy9uZy11bmx2LW9lL3NyYy91bmx2LW9lLWZvb3Rlci91bmx2LW9lLWZvb3Rlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9tdXJwaHkxMS9Eb2N1bWVudHMvd3d3L25nLXVubHYtb2Uvc3JjL3VubHYtb2UtZm9vdGVyL3VubHYtb2UtZm9vdGVyLnRzIiwibmc6Ly8vQzovVXNlcnMvbXVycGh5MTEvRG9jdW1lbnRzL3d3dy9uZy11bmx2LW9lL3NyYy91bmx2LW9lLWZvb3Rlci91bmx2LW9lLWZvb3Rlci50cy5Vbmx2T2VGb290ZXIuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL211cnBoeTExL0RvY3VtZW50cy93d3cvbmctdW5sdi1vZS9zcmMvdW5sdi1vZS1mb290ZXIvdW5sdi1vZS1mb290ZXIudHMuVW5sdk9lRm9vdGVyX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGZvb3RlciBjbGFzcz1cInVubHYtb2UtZm9vdGVyXCI+XG4gICAgXHQ8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgICAgIDxhIGhyZWY9XCIvL29ubGluZS51bmx2LmVkdVwiIHRhcmdldD1cIl9ibGFua1wiPjxpbWcgY2xhc3M9XCJvZS1sb2dvXCIgc3JjPVwiLy9vbmxpbmUudW5sdi5lZHUvc2l0ZXMvb25saW5lLnVubHYuZWR1Lm9lZHJ1cGFsL2xpYnJhcmllcy9iYXNlL09ubGluZV9FZHVjYXRpb25fNTAwd190cmltbWVkLnBuZ1wiIGFsdD1cIlVOTFYgT25saW5lIEVkdWNhdGlvbiBMb2dvXCI+PC9hPlxuICAgICAgICA8cCBjbGFzcz1cImNvcHlyaWdodFwiPlxuICAgIFx0XHRcdCZjb3B5OyB7e2NvcHlyaWdodH19IFVOTFYgT25saW5lIEVkdWNhdGlvblxuICAgIFx0XHQ8L3A+XG4gICAgXHQ8L2Rpdj5cbiAgICA8L2Zvb3Rlcj5cbiAgIiwiPHVubHYtb2UtZm9vdGVyPjwvdW5sdi1vZS1mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLDRDQUErQjtNQUM5QjtVQUFBO01BQXVCLCtDQUNwQjtVQUFBO1VBQUEsMERBQTRDO1VBQUE7Y0FBQTtVQUFBO01BQWtLLCtDQUM5TTtVQUFBO1VBQUEsNENBQXFCO1VBQUEsbURBRW5CO1VBQUEsY0FDQywyQ0FDRTtVQUFBOztJQUpnQjtJQUFBOzs7O29CQ0o3QjtNQUFBOzZCQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
