/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './unlv-oe-footer';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from '@angular/core/src/i18n/tokens';
import * as import6 from '@angular/core/src/linker/view';
import * as import7 from '@angular/core/src/render/api';
import * as import8 from '@angular/core/src/linker/view_utils';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/view_type';
import * as import11 from '@angular/core/src/change_detection/constants';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
class UnlvOeFooterModuleInjector extends import0.NgModuleInjector<import1.UnlvOeFooterModule> {
  _CommonModule_0:import2.CommonModule;
  _UnlvOeFooterModule_1:import1.UnlvOeFooterModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  constructor(parent:import4.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import5.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.UnlvOeFooterModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._UnlvOeFooterModule_1 = new import1.UnlvOeFooterModule();
    return this._UnlvOeFooterModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.UnlvOeFooterModule)) { return this._UnlvOeFooterModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UnlvOeFooterModuleNgFactory:import0.NgModuleFactory<import1.UnlvOeFooterModule> = new import0.NgModuleFactory(UnlvOeFooterModuleInjector,import1.UnlvOeFooterModule);
export class Wrapper_UnlvOeFooter {
  /*private*/ _eventHandler:Function;
  context:import1.UnlvOeFooter;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import1.UnlvOeFooter();
  }
  ngOnDetach(view:import6.AppView<any>,componentView:import6.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import6.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import6.AppView<any>,componentView:import6.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import6.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_UnlvOeFooter_Host:import7.RenderComponentType = import8.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{});
class View_UnlvOeFooter_Host0 extends import6.AppView<any> {
  _el_0:any;
  compView_0:import6.AppView<import1.UnlvOeFooter>;
  _UnlvOeFooter_0_3:Wrapper_UnlvOeFooter;
  constructor(viewUtils:import8.ViewUtils,parentView:import6.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UnlvOeFooter_Host0,renderType_UnlvOeFooter_Host,import10.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import11.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.ComponentRef<any> {
    this._el_0 = import8.selectOrCreateRenderHostElement(this.renderer,'unlv-oe-footer',import8.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_UnlvOeFooter0(this.viewUtils,this,0,this._el_0);
    this._UnlvOeFooter_0_3 = new Wrapper_UnlvOeFooter();
    this.compView_0.create(this._UnlvOeFooter_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import12.ComponentRef_<any>(0,this,this._el_0,this._UnlvOeFooter_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.UnlvOeFooter) && (0 === requestNodeIndex))) { return this._UnlvOeFooter_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UnlvOeFooter_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const UnlvOeFooterNgFactory:import12.ComponentFactory<import1.UnlvOeFooter> = new import12.ComponentFactory<import1.UnlvOeFooter>('unlv-oe-footer',View_UnlvOeFooter_Host0,import1.UnlvOeFooter);
const styles_UnlvOeFooter:any[] = ['.unlv-oe-footer[_ngcontent-%COMP%] {\n        height: 5.25rem;\n        width: 100%;\n        position: absolute;\n        left: 0;\n        bottom: 0;\n        text-align: center;\n        display: block;\n    }\n    .unlv-oe-footer[_ngcontent-%COMP%]   img.oe-logo[_ngcontent-%COMP%] {\n        max-width: 100%;\n        width: 300px;\n        margin-bottom: .25rem;\n    }\n    .unlv-oe-footer[_ngcontent-%COMP%]   p.copyright[_ngcontent-%COMP%] {\n        margin: 0;\n        font-size: .75rem;\n    }'];
var renderType_UnlvOeFooter:import7.RenderComponentType = import8.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_UnlvOeFooter,{});
export class View_UnlvOeFooter0 extends import6.AppView<import1.UnlvOeFooter> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import8.ViewUtils,parentView:import6.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UnlvOeFooter0,renderType_UnlvOeFooter,import10.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import11.ChangeDetectorStatus.CheckAlways);
    this._expr_13 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import12.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import8.createRenderElement(this.renderer,parentRenderNode,'footer',new import8.InlineArray2(2,'class','unlv-oe-footer'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    	',(null as any));
    this._el_3 = import8.createRenderElement(this.renderer,this._el_1,'div',new import8.InlineArray2(2,'class','container'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import8.createRenderElement(this.renderer,this._el_3,'a',new import8.InlineArray4(4,'href','//online.unlv.edu','target','_blank'),(null as any));
    this._el_6 = import8.createRenderElement(this.renderer,this._el_5,'img',new import8.InlineArray8(6,'alt','UNLV Online Education Logo','class','oe-logo','src','//online.unlv.edu/sites/online.unlv.edu.oedrupal/libraries/base/Online_Education_500w_trimmed.png'),(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_8 = import8.createRenderElement(this.renderer,this._el_3,'p',new import8.InlineArray2(2,'class','copyright'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n    	',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_13:any = import8.inlineInterpolate(1,'\n    			© ',this.context.copyright,' UNLV Online Education\n    		');
    if (import8.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_9,currVal_13);
      this._expr_13 = currVal_13;
    }
  }
}